/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DumbIntRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4872996571812157721L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DumbIntRequest\",\"namespace\":\"avro.model\",\"fields\":[{\"name\":\"val1\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DumbIntRequest> ENCODER =
      new BinaryMessageEncoder<DumbIntRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DumbIntRequest> DECODER =
      new BinaryMessageDecoder<DumbIntRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DumbIntRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DumbIntRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DumbIntRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DumbIntRequest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DumbIntRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DumbIntRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DumbIntRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DumbIntRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long val1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DumbIntRequest() {}

  /**
   * All-args constructor.
   * @param val1 The new value for val1
   */
  public DumbIntRequest(java.lang.Long val1) {
    this.val1 = val1;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return val1;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: val1 = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'val1' field.
   * @return The value of the 'val1' field.
   */
  public long getVal1() {
    return val1;
  }


  /**
   * Sets the value of the 'val1' field.
   * @param value the value to set.
   */
  public void setVal1(long value) {
    this.val1 = value;
  }

  /**
   * Creates a new DumbIntRequest RecordBuilder.
   * @return A new DumbIntRequest RecordBuilder
   */
  public static avro.model.DumbIntRequest.Builder newBuilder() {
    return new avro.model.DumbIntRequest.Builder();
  }

  /**
   * Creates a new DumbIntRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DumbIntRequest RecordBuilder
   */
  public static avro.model.DumbIntRequest.Builder newBuilder(avro.model.DumbIntRequest.Builder other) {
    if (other == null) {
      return new avro.model.DumbIntRequest.Builder();
    } else {
      return new avro.model.DumbIntRequest.Builder(other);
    }
  }

  /**
   * Creates a new DumbIntRequest RecordBuilder by copying an existing DumbIntRequest instance.
   * @param other The existing instance to copy.
   * @return A new DumbIntRequest RecordBuilder
   */
  public static avro.model.DumbIntRequest.Builder newBuilder(avro.model.DumbIntRequest other) {
    if (other == null) {
      return new avro.model.DumbIntRequest.Builder();
    } else {
      return new avro.model.DumbIntRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for DumbIntRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DumbIntRequest>
    implements org.apache.avro.data.RecordBuilder<DumbIntRequest> {

    private long val1;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.model.DumbIntRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.val1)) {
        this.val1 = data().deepCopy(fields()[0].schema(), other.val1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing DumbIntRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.model.DumbIntRequest other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.val1)) {
        this.val1 = data().deepCopy(fields()[0].schema(), other.val1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'val1' field.
      * @return The value.
      */
    public long getVal1() {
      return val1;
    }


    /**
      * Sets the value of the 'val1' field.
      * @param value The value of 'val1'.
      * @return This builder.
      */
    public avro.model.DumbIntRequest.Builder setVal1(long value) {
      validate(fields()[0], value);
      this.val1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'val1' field has been set.
      * @return True if the 'val1' field has been set, false otherwise.
      */
    public boolean hasVal1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'val1' field.
      * @return This builder.
      */
    public avro.model.DumbIntRequest.Builder clearVal1() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DumbIntRequest build() {
      try {
        DumbIntRequest record = new DumbIntRequest();
        record.val1 = fieldSetFlags()[0] ? this.val1 : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DumbIntRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<DumbIntRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DumbIntRequest>
    READER$ = (org.apache.avro.io.DatumReader<DumbIntRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.val1);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.val1 = in.readLong();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.val1 = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










