/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DumbIntRequest2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 382425680814030250L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DumbIntRequest2\",\"namespace\":\"avro.model\",\"fields\":[{\"name\":\"val1\",\"type\":\"long\"},{\"name\":\"val2\",\"type\":\"int\",\"default\":-1}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DumbIntRequest2> ENCODER =
      new BinaryMessageEncoder<DumbIntRequest2>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DumbIntRequest2> DECODER =
      new BinaryMessageDecoder<DumbIntRequest2>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DumbIntRequest2> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DumbIntRequest2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DumbIntRequest2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DumbIntRequest2>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DumbIntRequest2 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DumbIntRequest2 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DumbIntRequest2 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DumbIntRequest2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long val1;
   private int val2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DumbIntRequest2() {}

  /**
   * All-args constructor.
   * @param val1 The new value for val1
   * @param val2 The new value for val2
   */
  public DumbIntRequest2(java.lang.Long val1, java.lang.Integer val2) {
    this.val1 = val1;
    this.val2 = val2;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return val1;
    case 1: return val2;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: val1 = (java.lang.Long)value$; break;
    case 1: val2 = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'val1' field.
   * @return The value of the 'val1' field.
   */
  public long getVal1() {
    return val1;
  }


  /**
   * Sets the value of the 'val1' field.
   * @param value the value to set.
   */
  public void setVal1(long value) {
    this.val1 = value;
  }

  /**
   * Gets the value of the 'val2' field.
   * @return The value of the 'val2' field.
   */
  public int getVal2() {
    return val2;
  }


  /**
   * Sets the value of the 'val2' field.
   * @param value the value to set.
   */
  public void setVal2(int value) {
    this.val2 = value;
  }

  /**
   * Creates a new DumbIntRequest2 RecordBuilder.
   * @return A new DumbIntRequest2 RecordBuilder
   */
  public static avro.model.DumbIntRequest2.Builder newBuilder() {
    return new avro.model.DumbIntRequest2.Builder();
  }

  /**
   * Creates a new DumbIntRequest2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DumbIntRequest2 RecordBuilder
   */
  public static avro.model.DumbIntRequest2.Builder newBuilder(avro.model.DumbIntRequest2.Builder other) {
    if (other == null) {
      return new avro.model.DumbIntRequest2.Builder();
    } else {
      return new avro.model.DumbIntRequest2.Builder(other);
    }
  }

  /**
   * Creates a new DumbIntRequest2 RecordBuilder by copying an existing DumbIntRequest2 instance.
   * @param other The existing instance to copy.
   * @return A new DumbIntRequest2 RecordBuilder
   */
  public static avro.model.DumbIntRequest2.Builder newBuilder(avro.model.DumbIntRequest2 other) {
    if (other == null) {
      return new avro.model.DumbIntRequest2.Builder();
    } else {
      return new avro.model.DumbIntRequest2.Builder(other);
    }
  }

  /**
   * RecordBuilder for DumbIntRequest2 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DumbIntRequest2>
    implements org.apache.avro.data.RecordBuilder<DumbIntRequest2> {

    private long val1;
    private int val2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.model.DumbIntRequest2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.val1)) {
        this.val1 = data().deepCopy(fields()[0].schema(), other.val1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.val2)) {
        this.val2 = data().deepCopy(fields()[1].schema(), other.val2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing DumbIntRequest2 instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.model.DumbIntRequest2 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.val1)) {
        this.val1 = data().deepCopy(fields()[0].schema(), other.val1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.val2)) {
        this.val2 = data().deepCopy(fields()[1].schema(), other.val2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'val1' field.
      * @return The value.
      */
    public long getVal1() {
      return val1;
    }


    /**
      * Sets the value of the 'val1' field.
      * @param value The value of 'val1'.
      * @return This builder.
      */
    public avro.model.DumbIntRequest2.Builder setVal1(long value) {
      validate(fields()[0], value);
      this.val1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'val1' field has been set.
      * @return True if the 'val1' field has been set, false otherwise.
      */
    public boolean hasVal1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'val1' field.
      * @return This builder.
      */
    public avro.model.DumbIntRequest2.Builder clearVal1() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'val2' field.
      * @return The value.
      */
    public int getVal2() {
      return val2;
    }


    /**
      * Sets the value of the 'val2' field.
      * @param value The value of 'val2'.
      * @return This builder.
      */
    public avro.model.DumbIntRequest2.Builder setVal2(int value) {
      validate(fields()[1], value);
      this.val2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'val2' field has been set.
      * @return True if the 'val2' field has been set, false otherwise.
      */
    public boolean hasVal2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'val2' field.
      * @return This builder.
      */
    public avro.model.DumbIntRequest2.Builder clearVal2() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DumbIntRequest2 build() {
      try {
        DumbIntRequest2 record = new DumbIntRequest2();
        record.val1 = fieldSetFlags()[0] ? this.val1 : (java.lang.Long) defaultValue(fields()[0]);
        record.val2 = fieldSetFlags()[1] ? this.val2 : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DumbIntRequest2>
    WRITER$ = (org.apache.avro.io.DatumWriter<DumbIntRequest2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DumbIntRequest2>
    READER$ = (org.apache.avro.io.DatumReader<DumbIntRequest2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.val1);

    out.writeInt(this.val2);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.val1 = in.readLong();

      this.val2 = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.val1 = in.readLong();
          break;

        case 1:
          this.val2 = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










